"""add_next_reminder_at

Revision ID: 719a677ab6f0
Revises: 9afc72dade80
Create Date: 2026-07-07 19:45:53.360995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719a677ab6f0'
down_revision: Union[str, None] = '9afc72dade80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('next_reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'next_reminder_at')
    # ### end Alembic commands ###
